# Site settings
title: Sean M. Couch
description: Computational Nuclear Astrophysicist at Michigan State University
url: https://smcouch.github.io
author: Sean M. Couch
email: couch@pa.msu.edu
social:
  twitter: https://twitter.com/SeanMCouch
  github: https://github.com/smcouch
  bitbucket: https://bitbucket.org/smcouch
  youtube: https://www.youtube.com/user/SeanMCouch

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Build settings
markdown: kramdown

navbar:
  - name: Home
    url: /
  - name: Research
    url: /#research
  - name: Teaching
    url: /teaching.md
  - name: Publications
    url: /#publications
  - name: Code & Projects
    url: /projects.md
